//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBidder2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class buyer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public buyer()
        {
            this.placeBids = new HashSet<placeBid>();
        }
    
        public int buyerId { get; set; }
        public string buyerName { get; set; }
        public string buyerMail { get; set; }
        public string status { get; set; }
        public string password { get; set; }
        public string image { get; set; }
        public Nullable<int> bagId { get; set; }
    
        public virtual Bag Bag { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<placeBid> placeBids { get; set; }
    }
}
