//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OnlineBidder2.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    
    public partial class user
    {
        public int userId { get; set; }
        public string userName { get; set; }
        public string userMail { get; set; }
        public string status { get; set; }
        public string userPassword { get; set; }
        public string userImage { get; set; }
        public Nullable<int> bagId { get; set; }
    
        public virtual Bag Bag { get; set; }

        public HttpPostedFile ImageFile { get; set; }
    }
}
